### ISSUE TITLE
The Big Data Update Tracker

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/CelestiaContent#2]
This is the issue for tracking updates to all data files.

## Solar System
Check each object when its data, model (if any), and texture(s) (if any) have *all* been updated. I've made some suggestions for additional minor bodies to add to the default data files.
### solarsys.ssc
- [ ] Mercury
- [ ] Venus
- [ ] Earth
  - [ ] Moon
- [ ] Mars
  - [ ] Phobos
  - [ ] Deimos
- [ ] Jupiter
  - [ ] Io
  - [ ] Europa
  - [ ] Ganymede
  - [ ] Callisto
- [ ] Saturn
  - [ ] Mimas
  - [ ] Enceladus
  - [ ] Tethys
  - [ ] Dione
  - [ ] Rhea
  - [ ] Titan
  - [ ] Hyperion
  - [ ] Iapetus
  - [ ] Phoebe
- [ ] Uranus
  - [ ] Miranda
  - [ ] Ariel
  - [ ] Umbriel
  - [ ] Titania
  - [ ] Oberon
- [ ] Neptune
  - [ ] Proteus
  - [ ] Triton
  - [ ] Nereid
### dwarfplanets.ssc
I'm not sure this should really be a separate file - maybe dwarf planets should remain in asteroids.ssc and outersys.ssc, like in Project Echoes.
- [ ] Ceres
- [ ] Pluto
  - [ ] Charon
  - [ ] Styx
  - [ ] Nix
  - [ ] Kerberos
  - [ ] Hydra
- [ ] Haumea
  - [ ] Namaka
  - [ ] Hi'iaka
- [ ] Makemake
  - [ ] S/2015 (136472) 1 (MK2)
- [ ] Eris
  - [ ] Dysnomia
### asteroids.ssc
- [ ] 2 Pallas
- [ ] 3 Juno
- [ ] 4 Vesta
- [ ] 10 Hygiea (suggest adding)
- [ ] 21 Lutetia (suggest adding)
- [ ] 216 Kleopatra
  - [ ] Cleoselene (add)
  - [ ] Alexhelios (add)
- [ ] 243 Ida
  - [ ] Dactyl
- [ ] 253 Mathilde (add)
- [ ] 433 Eros
- [ ] 951 Gaspra
- [ ] 1620 Geographos
- [ ] 2063 Bacchus
- [ ] 2867 Šteins (suggest adding)
- [ ] 4179 Toutatis
- [ ] 4769 Castalia
- [ ] 5535 Annefrank (suggest adding)
- [ ] 6489 Golevka
- [ ] 9969 Braille (suggest adding)
- [ ] 25143 Itokawa
- [ ] 66391 Moshup (suggest adding)
  - [ ] Squannit (suggest adding)
- [ ] 101955 Bennu (suggest adding)
- [ ] 162173 Ryugu (suggest adding)
- [ ] 1998 KY26
### outersys.ssc
- [ ] 2060 Chiron (move from asteroids.ssc)
- [ ] 10199 Chariklo (suggest adding)
- [ ] 20000 Varuna
  - [ ] S/2019 (20000) 1 (add)
- [ ] 28978 Ixion
- [ ] 50000 Quaoar
  - [ ] Weywot (add)
- [ ] (55565) 2002 AW197
- [ ] 90377 Sedna
- [ ] 90482 Orcus
  - [ ] Vanth (add)
- [ ] 120347 Salacia (suggest adding)
  - [ ] Actaea (suggest adding)
- [ ] (225088) 2007 OR10 (Gonggong) (suggest adding)
  - [ ] S/2010 (225088) 1 (suggest adding)
- [ ] 486958 Arrokoth (suggest adding)
- [ ] 2004 XR190
- [ ] Probably add lots more large TNOs...
### comets.ssc
- [ ] 1P/Halley
- [ ] 9P/Tempel (suggest adding)
- [ ] 19P/Borrelly
- [ ] 67P/Churyumov-Gerasimenko (suggest adding)
- [ ] 81P/Wild (suggest adding)
- [ ] 103P/Hartley (suggest adding)
- [ ] 153P/Ikeya-Zhang
- [ ] C/1995 O1 Hale-Bopp
### minormoons.ssc
I'd suggest merging numberedmoons.ssc into minormoons.ssc. I'm not listing every single minor moon since there are so many - this file should include all planetary satellites not listed under the solarsys.ssc heading (yes, that does imply some moons being moved from solarsys.ssc).
- [ ] Jupiter's moons
- [ ] Saturn's moons
- [ ] Uranus' moons
- [ ] Neptune's moons
## Locations
I don't know if all of these files actually need to be updated; check them if they don't.
- [ ] Update merc_locs.ssc
- [ ] Update venus_locs.ssc
- [ ] earth_locs.ssc (obviously doesn't need an update)
- [ ] Update moon_locs.ssc
- [ ] Update mars_locs.ssc
- [ ] Update marsmoons_locs.ssc
- [ ] Update jupitermoons_locs.ssc
- [ ] Update saturnmoons_locs.ssc
- [ ] Update uranusmoons_locs.ssc
- [ ] Update neptunemoons_locs.ssc
- [ ] Update ring_locs.ssc
- [ ] Update world-capitals.ssc
- [ ] Add plutocharon_locs.ssc
- [ ] Add ceres_locs.ssc
- [ ] Update eros_locs.ssc
- [ ] Update gaspra_locs.ssc
- [ ] Update ida_locs.ssc
- [ ] Update itokawa_locs.ssc
- [ ] Add mathilde_locs.ssc
- [ ] Possibly add location files for other minor bodies
## Stars
- [ ] Update the main star database (stars.dat, hdxindex.dat, saoxindex.dat)
- [ ] Possibly add more cross-index files
- [ ] Update revised.stc
- [ ] Update nearstars.stc
- [ ] Update the binary star catalog
- [ ] Replace charm2.stc with jsdc.stc
## Exoplanets
- [ ] Update the exoplanet catalog
## DSOs
- [ ] Update galaxies.dsc(?)
- [ ] Update globulars.dsc(?)
- [ ] Add openclusters.dsc
## Spacecraft (extras-standard)
-fill in later-

Wow, that's a lot of stuff, and probably more I missed...

**Comment by SevenSpheres** [comment]
Maybe the Projects function could be used for this?

**Comment by 375gnu** [comment]
Projects is like releases, personally i don't see how to split this into projects.

**Comment by DaveBowman2001** [comment]
Mir should be checked as resolved now as per #286
